### ISSUE TITLE
colors not working on windows 10

### ISSUE THREAD

**Issue by pdbogen** [wttw/wowaddon#1]
Hi!

Not sure if you're expected the use of some other command shell, but the default command shell in windows 10 home does not appear to support colors.

<img width="674" alt="wowaddon-win10-colors" src="https://cloud.githubusercontent.com/assets/321591/19945702/8d6a6f5c-a0fe-11e6-815c-39027b6410eb.png">

**Comment by wttw** [comment]
Windows 10 used to support ansi colours, but they broke it in a recent update. The right thing to do is refactor and use windows-specific code for colour there. I've looked at it and the easy-to-use libraries don't work, and the libraries that work aren't that easy to use.

It's on my TODO list, or patches are welcome.
