### ISSUE TITLE
wowaddon assumes filesystem case-insensitivity

### ISSUE THREAD

**Issue by AbortRetryFail** [wttw/wowaddon#4]
This is a corner case. I'm running WoW on Wine in Linux. :)

Blizzard's installer calls the folder 'Interface/AddOns'
wowaddon looks for, and creates a different folder called 'Interface/Addons'

**Comment by wttw** [comment]
NTFS and mac are both case-insensitive so it's easy to miss bugs like that. Linux keeps us more honest. :)

I'll check the case of the paths and fix that up later today.

**Comment by AbortRetryFail** [comment]
I'm working around it with a symlink at the moment. Take your time. 👍

**Comment by wttw** [comment]
Fixed in 0.7.1, I think. I've added linux binaries to the packaging too, so it should be easier to test.
